### ISSUE TITLE
[Bug] Firmware crashes when changing RFTXPin

### ISSUE THREAD

**Issue by hhvrc** [OpenShock/Firmware#291]
### Pre-submission checklist

- [X] I checked that no other Bug Report describing my problem exists.
- [X] I am running the latest stable or prerelease firmware.
- [X] My board is on the [list of maintained boards](https://wiki.openshock.org/hardware/boards/#fully-maintained).
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### Board

OpenShock-Core-V2

### Firmware version

1.3.0

### Flashing method

OTA

### Describe what happened as precisely as possible.

Changed the pin, it saved correctly, then when swapping out the RFTransmitter instance it hits an assert in the destroy() function

### Describe what you expected to happen instead.

It would swap it out without issue

### In as much detail as possible, describe the exact steps you took to make the problem appear.

Set the RFTXPin during runtime

### Other remarks

```
[313456][I][RFTransmitter.cpp:96] ClearPendingCommands(): [RFTransmitter] [pin-1] Clearing pending commands

assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())


Backtrace: 0x40377a06:0x3fcc8060 0x4037c9d1:0x3fcc8080 0x40382bb5:0x3fcc80a0 0x4037d49b:0x3fcc81d0 0x4205afa2:0x3fcc8210 0x42027da0:0x3fcc8230 0x42027f61:0x3fcc8270 0x42003b87:0x3fcc8290 0x42024385:0x3fcc82d0 0x4201f2e3:0x3fcc8300 0x42002c12:0x3fcc8380 0x420f9c3a:0x3fcc83b0 0x4200b26d:0x3fcc83e0 0x4200b656:0x3fcc8410 0x420f9c6d:0x3fcc8430 0x42054bd5:0x3fcc8460 0x42054bfd:0x3fcc8490 0x420fab65:0x3fcc84b0 0x42055257:0x3fcc84d0 0x420fac3f:0x3fcc8500 0x42055585:0x3fcc8530 0x42055652:0x3fcc8560 0x420557da:0x3fcc8580 0x4205590e:0x3fcc85e0 0x42055585:0x3fcc8600 0x42055652:0x3fcc8630 0x420556c5:0x3fcc8650 0x4205587d:0x3fcc8690 0x4205590e:0x3fcc86f0 0x42055585:0x3fcc8710 0x42055652:0x3fcc8740 0x420556c5:0x3fcc8760 0x4205573a:0x3fcc87a0 0x420558f2:0x3fcc8800 0x42054add:0x3fcc8820 0x42054b92:0x3fcc8860 0x42054bb1:0x3fcc8880 0x4200288a:0x3fcc88a0 0x4200289d:0x3fcc88c0    
  #0  0x40377a06 in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
  #1  0x4037c9d1 in esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
  #2  0x40382bb5 in __assert_func at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:85
  #3  0x4037d49b in xQueueGenericSend at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:821 (discriminator 2)
  #4  0x4205afa2 in rmtDeinit at C:/Users/HeavenVR/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-rmt.c:352
  #5  0x42027da0 in OpenShock::RFTransmitter::destroy() at src/radio/RFTransmitter.cpp:129
  #6  0x42027f61 in OpenShock::RFTransmitter::~RFTransmitter() at src/radio/RFTransmitter.cpp:64
  #7  0x42003b87 in std::default_delete<OpenShock::RFTransmitter>::operator()(OpenShock::RFTransmitter*) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/unique_ptr.h:81
      (inlined by) std::unique_ptr<OpenShock::RFTransmitter, std::default_delete<OpenShock::RFTransmitter> >::reset(OpenShock::RFTransmitter*) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/unique_ptr.h:385
      (inlined by) std::unique_ptr<OpenShock::RFTransmitter, std::default_delete<OpenShock::RFTransmitter> >::operator=(decltype(nullptr)) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/unique_ptr.h:321
      (inlined by) OpenShock::CommandHandler::SetRfTxPin(unsigned char) at src/CommandHandler.cpp:212
  #8  0x42024385 in OpenShock::MessageHandlers::Local::_Private::HandleSetRfTxPinCommand(unsigned char, OpenShock::Serialization::Local::LocalToHubMessage const*) at src/event_handlers/websocket/local/SetRfTxPinCommand.cpp:38
  #9  0x4201f2e3 in OpenShock::EventHandlers::WebSocket::HandleLocalBinary(unsigned char, unsigned char const*, unsigned int) at src/event_handlers/websocket/Local.cpp:64
  #10 0x42002c12 in OpenShock::CaptivePortalInstance::handleWebSocketEvent(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int) at src/CaptivePortalInstance.cpp:189
  #11 0x420f9c3a in void std::__invoke_impl<void, void (OpenShock::CaptivePortalInstance::*&)(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), OpenShock::CaptivePortalInstance*&, unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int>(std::__invoke_memfun_deref, void (OpenShock::CaptivePortalInstance::*&)(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), OpenShock::CaptivePortalInstance*&, unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:73
      (inlined by) std::__invoke_result<void (OpenShock::CaptivePortalInstance::*&)(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), OpenShock::CaptivePortalInstance*&, unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int>::type std::__invoke<void (OpenShock::CaptivePortalInstance::*&)(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), OpenShock::CaptivePortalInstance*&, unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int>(void (OpenShock::CaptivePortalInstance::*&)(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), OpenShock::CaptivePortalInstance*&, unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:95
      (inlined by) void std::_Bind<void (OpenShock::CaptivePortalInstance::*(OpenShock::CaptivePortalInstance*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int)>::__call<void, unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&, 0u, 1u, 2u, 3u, 4u>(std::tuple<unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&>&&, std::_Index_tuple<0u, 1u, 2u, 3u, 4u>) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:400
      (inlined by) void std::_Bind<void (OpenShock::CaptivePortalInstance::*(OpenShock::CaptivePortalInstance*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int)>::operator()<unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int, void>(unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:484
      (inlined by) std::_Function_handler<void (unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int), std::_Bind<void (OpenShock::CaptivePortalInstance::*(OpenShock::CaptivePortalInstance*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int)> >::_M_invoke(std::_Any_data const&, unsigned char&&, OpenShock::WebSocketMessageType&&, unsigned char const*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297   
  #12 0x4200b26d in std::function<void (unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int)>::operator()(unsigned char, OpenShock::WebSocketMessageType, unsigned char const*, unsigned int) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
  #13 0x4200b656 in OpenShock::WebSocketDeFragger::handler(unsigned char, WStype_t, unsigned char const*, unsigned int) at src/WebSocketDeFragger.cpp:75
  #14 0x420f9c6d in void std::__invoke_impl<void, void (OpenShock::WebSocketDeFragger::*&)(unsigned char, WStype_t, unsigned char const*, unsigned int), OpenShock::WebSocketDeFragger*&, unsigned char, WStype_t, unsigned char*, unsigned int>(std::__invoke_memfun_deref, void (OpenShock::WebSocketDeFragger::*&)(unsigned char, WStype_t, unsigned char const*, unsigned int), OpenShock::WebSocketDeFragger*&, unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:73
      (inlined by) std::__invoke_result<void (OpenShock::WebSocketDeFragger::*&)(unsigned char, WStype_t, unsigned char const*, unsigned int), OpenShock::WebSocketDeFragger*&, unsigned char, WStype_t, unsigned char*, unsigned int>::type std::__invoke<void (OpenShock::WebSocketDeFragger::*&)(unsigned char, WStype_t, unsigned char const*, unsigned int), OpenShock::WebSocketDeFragger*&, unsigned char, WStype_t, unsigned char*, unsigned int>(void (OpenShock::WebSocketDeFragger::*&)(unsigned char, WStype_t, unsigned char const*, unsigned int), OpenShock::WebSocketDeFragger*&, unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:95
      (inlined by) void std::_Bind<void (OpenShock::WebSocketDeFragger::*(OpenShock::WebSocketDeFragger*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, WStype_t, unsigned char const*, unsigned int)>::__call<void, unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&, 0u, 1u, 2u, 3u, 4u>(std::tuple<unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&>&&, std::_Index_tuple<0u, 1u, 2u, 3u, 4u>) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:400
      (inlined by) void std::_Bind<void (OpenShock::WebSocketDeFragger::*(OpenShock::WebSocketDeFragger*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, WStype_t, unsigned char const*, unsigned int)>::operator()<unsigned char, WStype_t, unsigned char*, unsigned int, void>(unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:484
      (inlined by) std::_Function_handler<void (unsigned char, WStype_t, unsigned char*, unsigned int), std::_Bind<void (OpenShock::WebSocketDeFragger::*(OpenShock::WebSocketDeFragger*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>))(unsigned char, WStype_t, unsigned char const*, unsigned int)> >::_M_invoke(std::_Any_data const&, unsigned char&&, WStype_t&&, unsigned char*&&, unsigned int&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
  #15 0x42054bd5 in std::function<void (unsigned char, WStype_t, unsigned char*, unsigned int)>::operator()(unsigned char, WStype_t, unsigned char*, unsigned int) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
  #16 0x42054bfd in WebSocketsServerCore::runCbEvent(unsigned char, WStype_t, unsigned char*, unsigned int) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSocketsServer.h:181
  #17 0x420fab65 in WebSocketsServerCore::messageReceived(WSclient_t*, WSopcode_t, unsigned char*, unsigned int, bool) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSocketsServer.cpp:522
  #18 0x42055257 in WebSockets::handleWebsocketPayloadCb(WSclient_t*, bool, unsigned char*) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:488
  #19 0x420fac3f in void std::__invoke_impl<void, void (WebSockets::*&)(WSclient_t*, bool, unsigned char*), WebSockets*&, WSclient_t*, bool, unsigned char*&>(std::__invoke_memfun_deref, void (WebSockets::*&)(WSclient_t*, bool, unsigned char*), WebSockets*&, WSclient_t*&&, bool&&, unsigned char*&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:73
      (inlined by) std::__invoke_result<void (WebSockets::*&)(WSclient_t*, bool, unsigned char*), WebSockets*&, WSclient_t*, bool, unsigned char*&>::type std::__invoke<void (WebSockets::*&)(WSclient_t*, bool, unsigned char*), WebSockets*&, WSclient_t*, bool, unsigned char*&>(void (WebSockets::*&)(WSclient_t*, bool, unsigned char*), WebSockets*&, WSclient_t*&&, bool&&, unsigned char*&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:95
      (inlined by) void std::_Bind<void (WebSockets::*(WebSockets*, std::_Placeholder<1>, std::_Placeholder<2>, unsigned char*))(WSclient_t*, bool, unsigned char*)>::__call<void, WSclient_t*&&, bool&&, 0u, 1u, 2u, 3u>(std::tuple<WSclient_t*&&, bool&&>&&, std::_Index_tuple<0u, 1u, 2u, 3u>) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:400
      (inlined by) void std::_Bind<void (WebSockets::*(WebSockets*, std::_Placeholder<1>, std::_Placeholder<2>, unsigned char*))(WSclient_t*, bool, unsigned char*)>::operator()<WSclient_t*, bool, void>(WSclient_t*&&, bool&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:484
      (inlined by) std::_Function_handler<void (WSclient_t*, bool), std::_Bind<void (WebSockets::*(WebSockets*, std::_Placeholder<1>, std::_Placeholder<2>, unsigned char*))(WSclient_t*, bool, unsigned char*)> >::_M_invoke(std::_Any_data const&, WSclient_t*&&, bool&&) at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
  #20 0x42055585 in std::function<void (WSclient_t*, bool)>::operator()(WSclient_t*, bool) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
  #21 0x42055652 in WebSockets::readCb(WSclient_t*, unsigned char*, unsigned int, std::function<void (WSclient_t*, bool)>) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:657
  #22 0x420557da in WebSockets::handleWebsocketCb(WSclient_t*) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:462
  #23 0x4205590e in std::_Function_handler<void (WSclient_t*, bool), std::_Bind<WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int)::{lambda(WebSockets*, unsigned int, WSclient_t*, bool)#1} (WebSockets*, unsigned int, std::_Placeholder<1>, WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int)::{lambda(WebSockets*, unsigned int, WSclient_t*, bool)#1}<2>)> >::_M_invoke(std::_Any_data const&, WSclient_t*&&, bool&&) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:371
      (inlined by) __invoke_impl<void, WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)::<lambda(WebSockets*, size_t, WSclient_t*, bool)>&, WebSockets*&, unsigned int&, WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:60
      (inlined by) __invoke<WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)::<lambda(WebSockets*, size_t, WSclient_t*, bool)>&, WebSockets*&, unsigned int&, WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:95
      (inlined by) __call<void, WSclient_t*&&, bool&&, 0, 1, 2, 3> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:400
      (inlined by) operator()<WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:484
      (inlined by) _M_invoke at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
  #24 0x42055585 in std::function<void (WSclient_t*, bool)>::operator()(WSclient_t*, bool) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
  #25 0x42055652 in WebSockets::readCb(WSclient_t*, unsigned char*, unsigned int, std::function<void (WSclient_t*, bool)>) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:657
  #26 0x420556c5 in WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:367
  #27 0x4205587d in WebSockets::handleWebsocketCb(WSclient_t*) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:446
  #28 0x4205590e in std::_Function_handler<void (WSclient_t*, bool), std::_Bind<WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int)::{lambda(WebSockets*, unsigned int, WSclient_t*, bool)#1} (WebSockets*, unsigned int, std::_Placeholder<1>, WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int)::{lambda(WebSockets*, unsigned int, WSclient_t*, bool)#1}<2>)> >::_M_invoke(std::_Any_data const&, WSclient_t*&&, bool&&) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:371
      (inlined by) __invoke_impl<void, WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)::<lambda(WebSockets*, size_t, WSclient_t*, bool)>&, WebSockets*&, unsigned int&, WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:60
      (inlined by) __invoke<WebSockets::handleWebsocketWaitFor(WSclient_t*, size_t)::<lambda(WebSockets*, size_t, WSclient_t*, bool)>&, WebSockets*&, unsigned int&, WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/invoke.h:95
      (inlined by) __call<void, WSclient_t*&&, bool&&, 0, 1, 2, 3> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:400
      (inlined by) operator()<WSclient_t*, bool> at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0/functional:484
      (inlined by) _M_invoke at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
  #29 0x42055585 in std::function<void (WSclient_t*, bool)>::operator()(WSclient_t*, bool) const at c:\users\heavenvr\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
  #30 0x42055652 in WebSockets::readCb(WSclient_t*, unsigned char*, unsigned int, std::function<void (WSclient_t*, bool)>) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:657
  #31 0x420556c5 in WebSockets::handleWebsocketWaitFor(WSclient_t*, unsigned int) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:367
  #32 0x4205573a in WebSockets::handleWebsocketCb(WSclient_t*) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:395
  #33 0x420558f2 in WebSockets::handleWebsocket(WSclient_t*) at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSockets.cpp:343
  #34 0x42054add in WebSocketsServerCore::handleClientData() at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSocketsServer.cpp:688
  #35 0x42054b92 in WebSocketsServerCore::loop() at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSocketsServer.cpp:953
  #36 0x42054bb1 in WebSocketsServer::loop() at .pio/libdeps/OpenShock-Core-V2/WebSockets/src/WebSocketsServer.cpp:964
  #37 0x4200288a in OpenShock::CaptivePortalInstance::task() at src/CaptivePortalInstance.cpp:146 (discriminator 1)
  #38 0x4200289d in void OpenShock::Util::FnProxy<&OpenShock::CaptivePortalInstance::task>(void*) at include/util/FnProxy.h:24





ELF file SHA256: 2d064b0705af002c

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x420fbff2
  #0  0x420fbff2 in esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855

SPIWP:0xee
```

**Comment by nullstalgia** [comment]
What pin did you set it to, or is it when changing to any pin?
